### ISSUE TITLE
OpenApiRewriteIntegrationTest failure (because reusing port 3000)

### ISSUE THREAD

**Issue by rrayst** [membrane/api-gateway#1157]
Running `mvn verify` in the parent module leads to

```
-------------------------------------------------------------------------------
Test set: com.predic8.membrane.core.OpenApiRewriteIntegrationTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.749 s <<< FAILURE! -- in com.predic8.membrane.core.OpenApiRewriteIntegrationTest
com.predic8.membrane.core.OpenApiRewriteIntegrationTest.rewriteURLInOpenAPI -- Time elapsed: 0.679 s <<< ERROR!
com.predic8.membrane.core.transport.PortOccupiedException: Opening a serversocket at '*:3000' failed. Please make sure that the port is not occupied by a different program or change your rule configuration to select another one.
        at com.predic8.membrane.core.transport.http.HttpEndpointListener.<init>(HttpEndpointListener.java:106)
        at com.predic8.membrane.core.transport.http.HttpTransport.openPort(HttpTransport.java:171)
        at com.predic8.membrane.core.RuleManager.addProxyAndOpenPortIfNew(RuleManager.java:119)
        at com.predic8.membrane.core.RuleManager.addProxyAndOpenPortIfNew(RuleManager.java:111)
        at com.predic8.membrane.core.OpenApiRewriteIntegrationTest.setUp(OpenApiRewriteIntegrationTest.java:35)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
````

**Comment by rrayst** [comment]
still relevant (on master branch)
