### ISSUE TITLE
keyAlias is not yet supported

### ISSUE THREAD

**Issue by Thadir** [membrane/api-gateway#1238]
Goodday,

I am trying to set up a custom proxy and based on the documetation found [here](https://www.membrane-soa.org/api-gateway-doc/5.3/configuration/reference/keystore.htm):

I setup my sericeProxy as follows:
```xml
<serviceProxy name="SslClientForwardService">
   <path>SslClientForwardService</path>
   <ssl>
      <keystore keyAlias="SslClientForwardService" />
  </ssl>
</serviceProxy>
```

But when I run this I get the following stacktrace:
 15:44:21,515 DEBUG 1 main Router:141 - loading spring config: file:/app/conf/proxies.xml
 15:44:22,634 DEBUG 1 main RelocatingInterceptor:125 - protocol property set for WSDL Rewriting Interceptor:https
 15:44:22,639 DEBUG 1 main RelocatingInterceptor:125 - protocol property set for WSDL Rewriting Interceptor:https
 org.springframework.context.ApplicationContextException: Failed to start bean 'router'
    at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:291)
    at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:471)
    at java.base/java.lang.Iterable.forEach(Unknown Source)
    at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:260)
    at org.springframework.context.support.DefaultLifecycleProcessor.start(DefaultLifecycleProcessor.java:174)
    at org.springframework.context.support.AbstractApplicationContext.start(AbstractApplicationContext.java:1521)
    at com.predic8.membrane.core.Router.init(Router.java:147)
    at com.predic8.membrane.core.RouterCLI.main(RouterCLI.java:39)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at com.predic8.membrane.core.Starter.main(Starter.java:47)
 Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.security.InvalidParameterException: keyAlias is not yet supported.
    at com.predic8.membrane.core.Router.start(Router.java:316)
    at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:288)
    ... 12 more
 Caused by: java.lang.RuntimeException: java.security.InvalidParameterException: keyAlias is not yet supported.
    at com.predic8.membrane.core.transport.ssl.StaticSSLContext.<init>(StaticSSLContext.java:198)
    at com.predic8.membrane.core.rules.AbstractServiceProxy.init(AbstractServiceProxy.java:128)
    at com.predic8.membrane.core.rules.ServiceProxy.init(ServiceProxy.java:38)
    at com.predic8.membrane.core.rules.AbstractProxy.init(AbstractProxy.java:163)
    at com.predic8.membrane.core.Router.initRemainingRules(Router.java:269)
    at com.predic8.membrane.core.Router.init(Router.java:263)
    at com.predic8.membrane.core.Router.start(Router.java:288)
    ... 13 more
 Caused by: java.security.InvalidParameterException: keyAlias is not yet supported.
    at com.predic8.membrane.core.transport.ssl.StaticSSLContext.<init>(StaticSSLContext.java:89)
    ... 19 more

Witch is a bit counter productive as I see it in the doc available without the info that its not yet supported.

**Comment by rrayst** [comment]
Hi Thadir,

thanks for reporting this. You are absolutely right and we will look into that.

In the meantime, please use key stores with only one key entry and don't specify the `keyAlias` in Membrane's `proxies.xml`.

Thanks
Tobias

**Comment by Thadir** [comment]
Yeah this is the way it used to work.

But it makes it a bit clutterd it would be nice to just have one keystore to monitor. I sugest updating the documetation to represent this. And of course the major questino when will this feature be supported.

**Comment by t-burch** [comment]
@Thadir the feature is ready and will be merged soon
