### ISSUE TITLE
ACME error

### ISSUE THREAD

**Issue by rrayst** [membrane/api-gateway#1278]
```
2024-08-13T07:25:33.317813395Z 07:25:33,317  WARN 447 RouterThread /159.65.143.32:59234 AbstractHttpHandler:80 - An exception occured while handling a request:
2024-08-13T07:25:33.317847096Z java.lang.NullPointerException: Cannot invoke "Object.equals(Object)" because "this.testExpr" is null
2024-08-13T07:25:33.317851396Z  at com.predic8.membrane.core.openapi.serviceproxy.APIProxyKey.equals(APIProxyKey.java:114) ~[service-proxy-core-5.5.5-SNAPSHOT.jar:5.5.5-SNAPSHOT]
2024-08-13T07:25:33.317854996Z  at com.predic8.membrane.core.RuleManager.getRule(RuleManager.java:186) ~[service-proxy-core-5.5.5-SNAPSHOT.jar:5.5.5-SNAPSHOT]
2024-08-13T07:25:33.317857896Z  at com.predic8.membrane.core.RuleManager.exists(RuleManager.java:181) ~[service-proxy-core-5.5.5-SNAPSHOT.jar:5.5.5-SNAPSHOT]
2024-08-13T07:25:33.317879596Z  at com.predic8.membrane.core.RuleManager.addProxy(RuleManager.java:131) ~[service-proxy-core-5.5.5-SNAPSHOT.jar:5.5.5-SNAPSHOT]
2024-08-13T07:25:33.317882996Z  at com.predic8.membrane.core.RuleManager$1.add(RuleManager.java:358) ~[service-proxy-core-5.5.5-SNAPSHOT.jar:5.5.5-SNAPSHOT]
2024-08-13T07:25:33.317886296Z  at com.predic8.membrane.core.RuleManager$1.<init>(RuleManager.java:348) ~[service-proxy-core-5.5.5-SNAPSHOT.jar:5.5.5-SNAPSHOT]
2024-08-13T07:25:33.317889696Z  at com.predic8.membrane.core.RuleManager.getRulesBySource(RuleManager.java:342) ~[service-proxy-core-5.5.5-SNAPSHOT.jar:5.5.5-SNAPSHOT]
2024-08-13T07:25:33.317892696Z  at com.predic8.membrane.core.Router.getRules(Router.java:125) ~[service-proxy-core-5.5.5-SNAPSHOT.jar:5.5.5-SNAPSHOT]
2024-08-13T07:25:33.317910497Z  at com.predic8.membrane.core.interceptor.AcmeHttpChallengeInterceptor.handleRequest(AcmeHttpChallengeInterceptor.java:56) ~[service-proxy-core-5.5.5-SNAPSHOT.jar:5.5.5-SNAPSHOT]
2024-08-13T07:25:33.317913597Z  at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeRequestHandlers(InterceptorFlowController.java:111) ~[service-proxy-core-5.5.5-SNAPSHOT.jar:5.5.5-SNAPSHOT]
2024-08-13T07:25:33.317916497Z  at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeHandlers(InterceptorFlowController.java:76) ~[service-proxy-core-5.5.5-SNAPSHOT.jar:5.5.5-SNAPSHOT]
2024-08-13T07:25:33.317919297Z  at com.predic8.membrane.core.transport.http.AbstractHttpHandler.invokeHandlers(AbstractHttpHandler.java:61) ~[service-proxy-core-5.5.5-SNAPSHOT.jar:5.5.5-SNAPSHOT]
2024-08-13T07:25:33.317923697Z  at com.predic8.membrane.core.transport.http.HttpServerHandler.process(HttpServerHandler.java:227) ~[service-proxy-core-5.5.5-SNAPSHOT.jar:5.5.5-SNAPSHOT]
2024-08-13T07:25:33.317926597Z  at com.predic8.membrane.core.transport.http.HttpServerHandler.run(HttpServerHandler.java:128) ~[service-proxy-core-5.5.5-SNAPSHOT.jar:5.5.5-SNAPSHOT]
2024-08-13T07:25:33.317929397Z  at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
2024-08-13T07:25:33.317932197Z  at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
2024-08-13T07:25:33.317934997Z  at java.base/java.lang.Thread.run(Unknown Source) [?:?]
```

**Comment by rrayst** [comment]
probably solved by upgrading to `master`
