### ISSUE TITLE
Problems starting v5.7.4 on Linux and MacOS

### ISSUE THREAD

**Issue by rrayst** [membrane/api-gateway#1307]

**Comment by rrayst** [comment]
```
org.springframework.context.ApplicationContextException: Failed to start bean 'router'
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:288)
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:472)
        at java.base/java.lang.Iterable.forEach(Unknown Source)
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:257)
        at org.springframework.context.support.DefaultLifecycleProcessor.start(DefaultLifecycleProcessor.java:170)
        at org.springframework.context.support.AbstractApplicationContext.start(AbstractApplicationContext.java:1530)
        at com.predic8.membrane.core.Router.init(Router.java:147)
        at com.predic8.membrane.core.RouterCLI.main(RouterCLI.java:39)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at com.predic8.membrane.core.Starter.main(Starter.java:47)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at com.predic8.membrane.core.Router.start(Router.java:316)
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:285)
        ... 12 more
Caused by: java.lang.NullPointerException
        at java.base/java.io.FileInputStream.<init>(Unknown Source)
        at java.base/java.io.FileInputStream.<init>(Unknown Source)
        at com.predic8.membrane.core.openapi.util.Utils.getResourceAsStream(Utils.java:230)
        at com.predic8.membrane.core.openapi.serviceproxy.OpenAPIPublisherInterceptor.createTemplate(OpenAPIPublisherInterceptor.java:72)
        at com.predic8.membrane.core.openapi.serviceproxy.OpenAPIPublisherInterceptor.<init>(OpenAPIPublisherInterceptor.java:66)
        at com.predic8.membrane.core.openapi.serviceproxy.APIProxy.initOpenAPI(APIProxy.java:96)
        at com.predic8.membrane.core.openapi.serviceproxy.APIProxy.init(APIProxy.java:82)
        at com.predic8.membrane.core.rules.AbstractProxy.init(AbstractProxy.java:163)
        at com.predic8.membrane.core.Router.initRemainingRules(Router.java:269)
        at com.predic8.membrane.core.Router.init(Router.java:263)
        at com.predic8.membrane.core.Router.start(Router.java:288)
        ... 13 more
```
