### ISSUE TITLE
unify behaviour when 'connection closed' is received

### ISSUE THREAD

**Issue by rrayst** [membrane/api-gateway#261]
when this happends locally, a

```
java.net.SocketException: Software caused connection abort: recv failed
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    at java.net.SocketInputStream.read(SocketInputStream.java:170)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
    at com.predic8.membrane.core.util.HttpUtil.readLine(HttpUtil.java:54)
    at com.predic8.membrane.core.http.Response.parseStartLine(Response.java:318)
    at com.predic8.membrane.core.http.Response.read(Response.java:340)
    at com.predic8.membrane.core.transport.http.HttpClient.doCall(HttpClient.java:338)
    at com.predic8.membrane.core.transport.http.HttpClient.call(HttpClient.java:204)
    at com.predic8.membrane.core.interceptor.HTTPClientInterceptor.handleRequest(HTTPClientInterceptor.java:60)
    at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeRequestHandlers(InterceptorFlowController.java:106)
    at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeHandlers(InterceptorFlowController.java:71)
    at com.predic8.membrane.core.transport.http.AbstractHttpHandler.invokeHandlers(AbstractHttpHandler.java:70)
    at com.predic8.membrane.core.transport.http.HttpServerHandler.process(HttpServerHandler.java:223)
    at com.predic8.membrane.core.transport.http.HttpServerHandler.run(HttpServerHandler.java:112)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
```

is caught and currently retried

when this happens remotely, a

```
com.predic8.membrane.core.transport.http.NoResponseException: com.predic8.membrane.core.transport.http.EOFWhileReadingLineException: null line so far: ""
    at com.predic8.membrane.core.http.Response.parseStartLine(Response.java:321)
    at com.predic8.membrane.core.http.Response.read(Response.java:340)
    at com.predic8.membrane.core.transport.http.HttpClient.doCall(HttpClient.java:338)
    at com.predic8.membrane.core.transport.http.HttpClient.call(HttpClient.java:204)
    at com.predic8.membrane.core.interceptor.HTTPClientInterceptor.handleRequest(HTTPClientInterceptor.java:60)
    at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeRequestHandlers(InterceptorFlowController.java:106)
    at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeHandlers(InterceptorFlowController.java:71)
    at com.predic8.membrane.core.transport.http.AbstractHttpHandler.invokeHandlers(AbstractHttpHandler.java:70)
    at com.predic8.membrane.core.transport.http.HttpServerHandler.process(HttpServerHandler.java:223)
    at com.predic8.membrane.core.transport.http.HttpServerHandler.run(HttpServerHandler.java:112)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.predic8.membrane.core.transport.http.EOFWhileReadingLineException: null line so far: ""
    at com.predic8.membrane.core.util.HttpUtil.readLine(HttpUtil.java:69)
    at com.predic8.membrane.core.http.Response.parseStartLine(Response.java:318)
    ... 12 more
```

is caught and passed on (as a 'connection close') to the client.

behaviour should be unifed in both cases to retry the request iff it is not a POST.

**Comment by predic8** [comment]
Too old. Please reopen if still relevant.

**Comment by cagriman** [comment]
@predic8 @rrayst  i got this issue. do you remember which commit fixed this?

**Comment by nagarajan26** [comment]
@predic8 I got the same issue, Kindly provide the fix or pls explain the root, why it occurs
