### ISSUE TITLE
OutOfMemory in Tests

### ISSUE THREAD

**Issue by koin612** [membrane/api-gateway#538]
Seems not always to be the case. Running `mvn install` in root.

```
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.216 s - in com.predic8.membrane.core.rules.ProxySSLTest
[INFO] Running com.predic8.membrane.integration.SessionManager
[ERROR] unable to create native thread: possibly out of memory or process/resource limits reached
Exception in thread "main" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or process/resource limits reached
        at java.base/java.lang.Thread.start0(Native Method)
        at java.base/java.lang.Thread.start(Thread.java:802)
        at java.base/java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:945)
        at java.base/java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1593)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:346)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
        at org.apache.maven.surefire.booter.ForkedBooter.launchLastDitchDaemonShutdownThread(ForkedBooter.java:481)
        at org.apache.maven.surefire.booter.ForkedBooter.exit1(ForkedBooter.java:425)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:605)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)
```

**Comment by rrayst** [comment]
mac issue? @predic8 

building on Github works https://github.com/membrane/service-proxy/actions/runs/5057045330 (though that does not run *all* the tests to stay within the time limit)

**Comment by bridgerdier** [comment]
OOM also occurs on Github during Ubuntu build:
![Screenshot_20230525_215832](https://github.com/membrane/service-proxy/assets/8395870/3e49863c-eb37-4309-a243-ddedc0e50751)

**Comment by t-burch** [comment]
This seems to be fixed right? @koin612

**Comment by koin612** [comment]
> This seems to be fixed right? @koin612

I don't think so. Did not touch it and experienced OOM in Github and local builds.

**Comment by rrayst** [comment]
works with current infrastructure
