### ISSUE TITLE
% or %25 causes crash in the Web Server with 500 instead of 404

### ISSUE THREAD

**Issue by precoder** [membrane/api-gateway#759]
Hello,

With Version 4.9.1 and also with 5.2.0 a penetration test team managed to crash the Web Server by sending % or %25 on the path.
Here is an example serviceProxy from proxies.xml to reproduce it:

```
<router>
  <transport printStackTrace="true"/>
  <serviceProxy name="Example Rewriter Proxy" port="2000">
  <path>/</path>
    <rewriter>
      <map from="/hello.*" to="/index.html" />
    </rewriter>
   <webServer docBase="../client" index="index.html"/>
   </serviceProxy>
</router>
```

Directly in the Membrane main folder I created a "client" directory with index.html in it with simple content such as Hello for testing.
http://localhost:2000/hello -> Returns 200 with content Hello from index,html
http://localhost:2000/lalala -> Returns 404 Not Found.

http://localhost:2000/% -> Returns 500 due to Parsing Error for invalid URL.
I enabled the Stack Trace and we get:
```
java.net.URISyntaxException: Malformed escape pair at index 1: /%
	at java.base/java.net.URI$Parser.fail(URI.java:2974)
	at java.base/java.net.URI$Parser.scanEscape(URI.java:3102)
	at java.base/java.net.URI$Parser.scan(URI.java:3125)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3143)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3227)
	at java.base/java.net.URI$Parser.parse(URI.java:3186)
	at java.base/java.net.URI.<init>(URI.java:623)
	at com.predic8.membrane.core.util.URI.<init>(URI.java:48)
	at com.predic8.membrane.core.util.URIFactory.create(URIFactory.java:58)
	at com.predic8.membrane.core.util.URLUtil.getPathQuery(URLUtil.java:30)
	at com.predic8.membrane.core.interceptor.rewrite.RewriteInterceptor.handleRequest(RewriteInterceptor.java:151)
	at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeRequestHandlers(InterceptorFlowController.java:110)
	at com.predic8.membrane.core.interceptor.UserFeatureInterceptor.handleRequest(UserFeatureInterceptor.java:47)
	at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeRequestHandlers(InterceptorFlowController.java:110)
	at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeHandlers(InterceptorFlowController.java:75)
	at com.predic8.membrane.core.transport.http.AbstractHttpHandler.invokeHandlers(AbstractHttpHandler.java:61)
	at com.predic8.membrane.core.transport.http.HttpServerHandler.process(HttpServerHandler.java:227)
	at com.predic8.membrane.core.transport.http.HttpServerHandler.run(HttpServerHandler.java:128)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
http://localhost:2000/%25 -> Returns 500 due to Parsing Error for invalid URL.
We get a bit different Stack Trace but the source of the Problem seems same.
```
java.net.URISyntaxException: Malformed escape pair at index 1: /%
	at java.base/java.net.URI$Parser.fail(URI.java:2974)
	at java.base/java.net.URI$Parser.scanEscape(URI.java:3102)
	at java.base/java.net.URI$Parser.scan(URI.java:3125)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3143)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3227)
	at java.base/java.net.URI$Parser.parse(URI.java:3186)
	at java.base/java.net.URI.<init>(URI.java:623)
	at com.predic8.membrane.core.util.URI.<init>(URI.java:48)
	at com.predic8.membrane.core.util.URIFactory.create(URIFactory.java:58)
	at com.predic8.membrane.core.interceptor.server.WebServerInterceptor.handleRequest(WebServerInterceptor.java:90)
	at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeRequestHandlers(InterceptorFlowController.java:110)
	at com.predic8.membrane.core.interceptor.UserFeatureInterceptor.handleRequest(UserFeatureInterceptor.java:47)
	at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeRequestHandlers(InterceptorFlowController.java:110)
	at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeHandlers(InterceptorFlowController.java:75)
	at com.predic8.membrane.core.transport.http.AbstractHttpHandler.invokeHandlers(AbstractHttpHandler.java:61)
	at com.predic8.membrane.core.transport.http.HttpServerHandler.process(HttpServerHandler.java:227)
	at com.predic8.membrane.core.transport.http.HttpServerHandler.run(HttpServerHandler.java:128)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

I think Web Server should return 404 for the non existing or invalid URL paths.
This is also default behavior of other Web Servers such as Nginx.

When stack traces are disabled, an attacker can still see Membrane Web Server is running on the target Server if an error occurs.
Do you have a way to replace the default 500 Error Page with empty page or some other page/footer to prevent information exposure in case of an error occurs?

**Comment by predic8** [comment]
Thanks @precoder for the report. 

@t-burch Can you write a test for the rewriter interceptor and test this behaviour?


One Question: Did Membrane crash or did it just return an error message or stacktrace?

**Comment by precoder** [comment]
it just return an error message, but process continues to run, sorry for misunderstanding Process did not crashed.

**Comment by precoder** [comment]
Now I checked it again, I also get `400 Bad Request` for the called URLs with `Internal Server Error` page. Since I see the `Internal Server Error` I automatically thought it was 500. Maybe a different page for 400 and 500 codes would be nice to distinguish it directly without causing a misleading like I had.

Sorry for confusion.

**Comment by precoder** [comment]
As a workaround for now on 4.9.1 I created an empty body for 400 Bad Request Responses.
Once you provide a better solution on the latest version, we can switch to use it on the latest version.

```
diff --git a/core/src/main/java/com/predic8/membrane/core/transport/http/AbstractHttpHandler.java b/core/src/main/java/com/predic8/membrane/core/transport/http/AbstractHttpHandler.java
index f51b3208..381de847 100644
--- a/core/src/main/java/com/predic8/membrane/core/transport/http/AbstractHttpHandler.java
+++ b/core/src/main/java/com/predic8/membrane/core/transport/http/AbstractHttpHandler.java
@@ -151,7 +151,12 @@ public abstract class AbstractHttpHandler  {
                                                build();
                                break;
                        case UNKNOWN:
-                               error = HttpUtil.setHTMLErrorResponse(b, msg, comment);
+                               if (e instanceof URISyntaxException) {
+                                       error = b.
+                                                 build();
+                               } else {
+                                       error = HttpUtil.setHTMLErrorResponse(b, msg, comment);
+                               }
                                break;
                }
                return error;
```

**Comment by t-burch** [comment]
After internal review, it is now decided that there will be now implementation of the debranding, and the error return format of the rewriter plugin will be changed to problem json reflecting the error without stacktrace.


For returning a blank or custom page a script snippet can be used like this:
```groovy
<groovy>
   if (flow == com.predic8.membrane.core.interceptor.Interceptor.Flow.ABORT) {
      exc.setResponse(Response.notFound().build());
   }
</groovy>
```
When inserted at the beginning of the flow, it will hide any errors that will occur behind a blank/custom page.
