### ISSUE TITLE
java.lang.NullPointerException AbstractHttpHandler

### ISSUE THREAD

**Issue by svenlange** [membrane/api-gateway#853]
23:56:43,871  WARN 34 RouterThread /192.168.65.1:30070 AbstractHttpHandler:80 - An exception occured while handling a request: 
java.lang.reflect.InvocationTargetException: null
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
    at com.predic8.membrane.core.interceptor.rest.RESTInterceptor.dispatchRequest(RESTInterceptor.java:83) ~[service-proxy-core-5.2.0.jar:5.2.0]
    at com.predic8.membrane.core.interceptor.rest.RESTInterceptor.handleRequest(RESTInterceptor.java:56) ~[service-proxy-core-5.2.0.jar:5.2.0]
    at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeRequestHandlers(InterceptorFlowController.java:110) ~[service-proxy-core-5.2.0.jar:5.2.0]
    at com.predic8.membrane.core.interceptor.administration.AdminConsoleInterceptor.handleRequest(AdminConsoleInterceptor.java:54) ~[service-proxy-core-5.2.0.jar:5.2.0]
    at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeRequestHandlers(InterceptorFlowController.java:110) ~[service-proxy-core-5.2.0.jar:5.2.0]
    at com.predic8.membrane.core.interceptor.UserFeatureInterceptor.handleRequest(UserFeatureInterceptor.java:47) ~[service-proxy-core-5.2.0.jar:5.2.0]
    at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeRequestHandlers(InterceptorFlowController.java:110) ~[service-proxy-core-5.2.0.jar:5.2.0]
    at com.predic8.membrane.core.interceptor.InterceptorFlowController.invokeHandlers(InterceptorFlowController.java:75) ~[service-proxy-core-5.2.0.jar:5.2.0]
    at com.predic8.membrane.core.transport.http.AbstractHttpHandler.invokeHandlers(AbstractHttpHandler.java:61) [service-proxy-core-5.2.0.jar:5.2.0]
    at com.predic8.membrane.core.transport.http.HttpServerHandler.process(HttpServerHandler.java:227) [service-proxy-core-5.2.0.jar:5.2.0]
    at com.predic8.membrane.core.transport.http.HttpServerHandler.run(HttpServerHandler.java:128) [service-proxy-core-5.2.0.jar:5.2.0]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
    at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "com.predic8.membrane.core.http.Request.getHeader()" because the return value of "com.predic8.membrane.core.exchange.AbstractExchange.getRequest()" is null
    at com.predic8.membrane.core.exchangestore.AbstractExchangeStore.requestHeaderContains(AbstractExchangeStore.java:186) ~[service-proxy-core-5.2.0.jar:5.2.0]
    at com.predic8.membrane.core.exchangestore.AbstractExchangeStore.filterExchanges(AbstractExchangeStore.java:172) ~[service-proxy-core-5.2.0.jar:5.2.0]
    at com.predic8.membrane.core.exchangestore.AbstractExchangeStore.lambda$filter$0(AbstractExchangeStore.java:146) ~[service-proxy-core-5.2.0.jar:5.2.0]
    at java.util.stream.ReferencePipeline$2$1.accept(Unknown Source) ~[?:?]
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:?]
    at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:?]
    at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:?]
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source) ~[?:?]
    at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:?]
    at java.util.stream.ReferencePipeline.collect(Unknown Source) ~[?:?]
    at com.predic8.membrane.core.exchangestore.AbstractExchangeStore.filter(AbstractExchangeStore.java:161) ~[service-proxy-core-5.2.0.jar:5.2.0]
    at com.predic8.membrane.core.exchangestore.AbstractExchangeStore.getFilteredSortedPaged(AbstractExchangeStore.java:108) ~[service-proxy-core-5.2.0.jar:5.2.0]
    at com.predic8.membrane.core.interceptor.administration.AdminRESTInterceptor.getExchanges(AdminRESTInterceptor.java:232) ~[service-proxy-core-5.2.0.jar:5.2.0]
    ... 18 more

**Comment by rrayst** [comment]
Hi Sven,

how did you get `exchange.request` to be set to `null`? Membrane on its own should not (and does not, as far as I can see) set it to `null`.

Best
Tobias
