### ISSUE TITLE
fix two tests APIKey*Test: Windows/Linux problem

### ISSUE THREAD

**Issue by rrayst** [membrane/api-gateway#860]

**Comment by predic8** [comment]
@rrayst Errors can't be reproduced. Can you run the tests an post the assertions that go wrong?

**Comment by rrayst** [comment]
`APIKeysInterceptorTest`

```
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/u4786436/git/membrane/service-proxy/core/target/test-classes/apikeys/keys.txt

	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at com.predic8.membrane.core.interceptor.apikey.ApiKeyUtils.readFile(ApiKeyUtils.java:23)
	at com.predic8.membrane.core.interceptor.apikey.stores.ApiKeyFileStore.onApplicationEvent(ApiKeyFileStore.java:41)
	at com.predic8.membrane.core.interceptor.apikey.ApiKeysInterceptorTest.setup(ApiKeysInterceptorTest.java:50)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```

**Comment by rrayst** [comment]
`ApiKeySecurityValidatorTest`

```
org.opentest4j.AssertionFailedError: 
Expected :1
Actual   :0
<Click to see difference>


	at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
	at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:145)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:527)
	at com.predic8.membrane.core.openapi.validators.security.ApiKeySecurityValidatorTest.inHeaderWrongName(ApiKeySecurityValidatorTest.java:62)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
```
