### ISSUE TITLE
NullPointer in oauth2

### ISSUE THREAD

**Issue by russelmrcl** [membrane/api-gateway#865]
```
java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "com.predic8.membrane.core.interceptor.session.Session.get(String)" is null
	at com.predic8.membrane.core.interceptor.oauth2client.SessionOriginalExchangeStore.reconstruct(SessionOriginalExchangeStore.java:50)
	at com.predic8.membrane.core.interceptor.oauth2client.rf.OAuth2CallbackRequestHandler.handleRequest(OAuth2CallbackRequestHandler.java:97)
	at com.predic8.membrane.core.interceptor.oauth2client.OAuth2Resource2Interceptor.handleRequest(OAuth2Resource2Interceptor.java:281)
```

**Comment by predic8** [comment]
@russelmrcl can you provide some context or background info to the error message?
