### ISSUE TITLE
Membrane does not start on Windows, if there is a space in the base path

### ISSUE THREAD

**Issue by rrayst** [membrane/api-gateway#910]
on Windows, if there is a space in the base path, we should issue a warning.

**Comment by t-burch** [comment]
Could not replicate anymore.
Tried starting Membrane on Windows with many spaces and symbols and it worked fine.

**Comment by rrayst** [comment]
```
C:\Users\TobiasPolley\Downloads\membrane-api gateway-5.7.3\membrane-api-gateway-5.7.3>service-proxy.bat
"You are running Java 0. Membrane needs atleast Java 8. Please install a newer Java version from http://www.oracle.com/technetwork/java/javase/downloads/index.html"
Membrane Router running...
Standard Commons Logging discovery in action with spring-jcl: please remove commons-logging.jar from classpath in order to avoid potential conflicts
12:24:52,543  INFO 1 main OpenAPIRecordFactory:83 - Parsing spec fruitshop-api.yml
org.springframework.context.ApplicationContextException: Failed to start bean 'router'
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:288)
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:469)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:257)
        at org.springframework.context.support.DefaultLifecycleProcessor.start(DefaultLifecycleProcessor.java:170)
        at org.springframework.context.support.AbstractApplicationContext.start(AbstractApplicationContext.java:1530)
        at com.predic8.membrane.core.Router.init(Router.java:147)
        at com.predic8.membrane.core.RouterCLI.main(RouterCLI.java:39)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at com.predic8.membrane.core.Starter.main(Starter.java:47)
Caused by: BUG! exception in phase 'semantic analysis' in source unit 'StreamingTemplateScript1.groovy' null
        at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:901)
        at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:692)
        at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:666)
        at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:373)
        at groovy.lang.GroovyClassLoader.lambda$parseClass$2(GroovyClassLoader.java:316)
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
        at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
        at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:298)
        at groovy.text.StreamingTemplateEngine$StreamingTemplate.createTemplateClosure(StreamingTemplateEngine.java:607)
        at groovy.text.StreamingTemplateEngine$StreamingTemplate.<init>(StreamingTemplateEngine.java:522)
        at groovy.text.StreamingTemplateEngine.createTemplate(StreamingTemplateEngine.java:220)
        at com.predic8.membrane.core.openapi.serviceproxy.OpenAPIPublisherInterceptor.createTemplate(OpenAPIPublisherInterceptor.java:72)
        at com.predic8.membrane.core.openapi.serviceproxy.OpenAPIPublisherInterceptor.<init>(OpenAPIPublisherInterceptor.java:66)
        at com.predic8.membrane.core.openapi.serviceproxy.APIProxy.initOpenAPI(APIProxy.java:96)
        at com.predic8.membrane.core.openapi.serviceproxy.APIProxy.init(APIProxy.java:82)
        at com.predic8.membrane.core.rules.AbstractProxy.init(AbstractProxy.java:163)
        at com.predic8.membrane.core.Router.initRemainingRules(Router.java:269)
        at com.predic8.membrane.core.Router.init(Router.java:263)
        at com.predic8.membrane.core.Router.start(Router.java:288)
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:285)
        ... 10 more
Caused by: groovy.lang.GroovyRuntimeException
        at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:74)
        at org.codehaus.groovy.control.ClassNodeResolver.findDecompiled(ClassNodeResolver.java:255)
        at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:193)
        at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:175)
        at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:129)
        at org.codehaus.groovy.control.ResolveVisitor.resolveToOuter(ResolveVisitor.java:769)
        at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:410)
        at org.codehaus.groovy.control.ResolveVisitor.resolveFromDefaultImports(ResolveVisitor.java:564)
        at org.codehaus.groovy.control.ResolveVisitor.resolveFromDefaultImports(ResolveVisitor.java:533)
        at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:409)
        at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:371)
        at org.codehaus.groovy.control.ResolveVisitor.resolveOrFail(ResolveVisitor.java:339)
        at org.codehaus.groovy.control.ResolveVisitor.resolveOrFail(ResolveVisitor.java:328)
        at org.codehaus.groovy.control.ResolveVisitor.resolveOrFail(ResolveVisitor.java:324)
        at org.codehaus.groovy.control.ResolveVisitor.transformConstructorCallExpression(ResolveVisitor.java:1120)
        at org.codehaus.groovy.control.ResolveVisitor.transform(ResolveVisitor.java:800)
        at org.codehaus.groovy.control.ResolveVisitor.transformBinaryExpression(ResolveVisitor.java:1092)
        at org.codehaus.groovy.control.ResolveVisitor.transform(ResolveVisitor.java:794)
        at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitExpressionStatement(ClassCodeExpressionTransformer.java:129)
        at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:41)
        at org.codehaus.groovy.ast.CodeVisitorSupport.visitBlockStatement(CodeVisitorSupport.java:86)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitBlockStatement(ClassCodeVisitorSupport.java:168)
        at org.codehaus.groovy.control.ResolveVisitor.visitBlockStatement(ResolveVisitor.java:1373)
        at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:72)
        at org.codehaus.groovy.ast.CodeVisitorSupport.visitTryCatchFinally(CodeVisitorSupport.java:133)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitTryCatchFinally(ClassCodeVisitorSupport.java:246)
        at org.codehaus.groovy.ast.stmt.TryCatchStatement.visit(TryCatchStatement.java:48)
        at org.codehaus.groovy.ast.CodeVisitorSupport.visitBlockStatement(CodeVisitorSupport.java:86)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitBlockStatement(ClassCodeVisitorSupport.java:168)
        at org.codehaus.groovy.control.ResolveVisitor.visitBlockStatement(ResolveVisitor.java:1373)
        at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:72)
        at org.codehaus.groovy.control.ResolveVisitor.transformClosureExpression(ResolveVisitor.java:1112)
        at org.codehaus.groovy.control.ResolveVisitor.transform(ResolveVisitor.java:798)
        at org.codehaus.groovy.control.ResolveVisitor.transformMethodCallExpression(ResolveVisitor.java:1136)
        at org.codehaus.groovy.control.ResolveVisitor.transform(ResolveVisitor.java:796)
        at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitReturnStatement(ClassCodeExpressionTransformer.java:147)
        at org.codehaus.groovy.ast.stmt.ReturnStatement.visit(ReturnStatement.java:73)
        at org.codehaus.groovy.ast.CodeVisitorSupport.visitBlockStatement(CodeVisitorSupport.java:86)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitBlockStatement(ClassCodeVisitorSupport.java:168)
        at org.codehaus.groovy.control.ResolveVisitor.visitBlockStatement(ResolveVisitor.java:1373)
        at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:72)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:142)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:115)
        at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitConstructorOrMethod(ClassCodeExpressionTransformer.java:87)
        at org.codehaus.groovy.control.ResolveVisitor.visitConstructorOrMethod(ResolveVisitor.java:292)
        at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitMethod(ClassCodeVisitorSupport.java:110)
        at org.codehaus.groovy.ast.ClassNode.visitMethods(ClassNode.java:1132)
        at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1125)
        at org.codehaus.groovy.control.ResolveVisitor.visitClass(ResolveVisitor.java:1302)
        at org.codehaus.groovy.control.ResolveVisitor.startResolving(ResolveVisitor.java:258)
        at org.codehaus.groovy.control.CompilationUnit.lambda$addPhaseOperations$4(CompilationUnit.java:218)
        at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:897)
        ... 30 more
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 53: jar:file:C:/Users/TobiasPolley/Downloads/membrane-api gateway-5.7.3/membrane-api-gateway-5.7.3/lib/groovy-4.0.22.jar!/groovy/lang/Binding.class
        at java.base/java.net.URI$Parser.fail(URI.java:2995)
        at java.base/java.net.URI$Parser.checkChars(URI.java:3166)
        at java.base/java.net.URI$Parser.parse(URI.java:3202)
        at java.base/java.net.URI.<init>(URI.java:645)
        at java.base/java.net.URL.toURI(URL.java:1220)
        at org.codehaus.groovy.ast.decompiled.AsmDecompiler.parseClass(AsmDecompiler.java:72)
        ... 81 more

```
